server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/mescuderop/config_server.git
          search-paths: config-data
  aplication:
    name: config-service
